package com.technopreneur.moneytransfer.event;

public enum EventType {

    TRANSACTION_QUEUED_EVENT,
    TRANSACTION_STARTED_EVENT,
    TRANSACTION_COMPLETED_EVENT,
    TRANSACTION_DEBIT_STARTED_EVENT,
    TRANSACTION_DEBIT_COMPLETED_EVENT,
    TRANSACTION_CREDIT_STARTED_EVENT,
    TRANSACTION_CREDIT_COMPLETED_EVENT,
    TRANSACTION_FAILED_EVENT,
    TRANSACTION_DEBIT_FAILED_EVENT,
    TRANSACTION_CREDIT_FAILED_EVENT
}
